export const MESSAGES = {
    ACCOUNT_CREATE_SUCCESS: 'ACCOUNT_CREATED_SUCCESSFULLY',
    ACCOUNT_CREATE_FAIL: 'CREATE_ACCOUNT_FAIL',
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    LOGIN_SUCCESS: 'LOGIN_SUCCESSFULLY'
};

export const ACCOUNTTYPE = {
    USER: 'USER',
    ADMIN: 'ADMIN',
};
